export enum EntityNames {
  User = "user",
  Otp = "otp",
  Course = "course",
  CourseCategory = "course_category",
  CourseComment = "course_comment",
  Category = "category",
  Chapter = "chapter",
  Sesstion = "sesstion",
  Blog = "blog",
  BlogLikes = "blog_likes",
  BlogBookmarks = "blog_bookmark",
  BlogComments = "blog_comments",
  BlogCategory = "blog_category",
  Comment = "comment",
  Discount = "discount",
  Basket = "basket",
  Order = "order",
  OrderItem = "order_item",
  Payment = "payment",
}
